### ISSUE TITLE
Missing models in Khune (a player house mod included in the modlist)

### ISSUE THREAD

**Issue by AichiChikuwa** [GuitarBarbarianOfThunder/eldersouls#103] opened 2020-05-25 20:44 UTC
**Describe the bug**
Furniture models are missing in [Khune](https://www.nexusmods.com/skyrim/mods/59227?tab=description)

**To Reproduce**
1. _tmm 1_ to get the map marker for the house, which is at somewhere southwest.
2. _unlock_ to get inside.
3. missing models can be seen mostly in the enchanting room, but there are tiny missing parts elsewhere in the house.

**Expected behavior**
Models should be loaded as [one of the screenshots](https://staticdelivery.nexusmods.com/mods/110/images/59227-1-1413909294.png) the original mod page shows.

**Screenshots**
![1145](https://user-images.githubusercontent.com/65875548/82841249-620b7f80-9ea3-11ea-8909-2084fbf00ee4.png)

**Modlist version**
1.1.7
**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment] 2020-05-26 03:28
Re-install the mod please by rightclicking it and choosing reinstall.. Then disable the esp.  Let me know if the problem is resolved after that?  I think the place is fine but I might have been overzealous when I was removing some duplicate meshes a few updates ago.

**Comment by jdsmith2816** [comment] 2020-06-19 08:15
Fixed in 1.1.12

**Closed by jdsmith2816** 2020-06-19 08:15 UTC
